### ISSUE TITLE
Error on final message

### ISSUE THREAD

**Issue by stacksjb** [DividedGibon/Facebook_Messages_Bulk#2]
Not a big deal as it works very well - thanks for writing this! 💯 

When I run it, it throws error "Cannot read properties of undefined (reading 'click')/  Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs." when it gets to the last message, leaving one final message in the box. 

(Of course, it's easy to delete the last one manually and this might be by design, since there is no way to know how many), but wanted to check/note.

Thanks!

**Comment by DividedGibon** [comment]
> Not a big deal as it works very well - thanks for writing this! 💯 
> 
> 
> 
> When I run it, it throws error "Cannot read properties of undefined (reading 'click')/  Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs." when it gets to the last message, leaving one final message in the box. 
> 
> 
> 
> (Of course, it's easy to delete the last one manually and this might be by design, since there is no way to know how many), but wanted to check/note.
> 
> 
> 
> Thanks!

Thanks for the issue raise. 

Yes, very good point, and something I'll make clear in the readme.  The error you get is because we're using "browser debugging" or "browser hacking" to interact with the website. I.e. not using an official API.  It can just be ignored and would be expected. 

Strange about the last chat being left though.  I'll look at the code and see if it's missing the last loop. Cheers

Thanks Again, DG
